---
title: Ben Carr | Software Developer
description: Software developer at Sky and graduate from The University of Sheffield. This is my slice of the internet.
url: "https://benjy2429.github.io"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - node_modules
  - README.md
  - gulpfile.js
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
