---
title: Ben Carr | Software Developer
description: Software developer currently working for Sky and graduate from The University of Sheffield.
url: "https://benjy2429.github.io"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - node_modules
  - README.md
  - webpack.config.js
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
