---
title: Ben Carr | Developer
email: ben-carr7@hotmail.com
description: Personal website for Ben Carr
url: "https://benjy2429.github.io"
github_username: benjy2429

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
